server {
    listen 443 ssl;
    http2 on;

    server_name utkarshtyagi.in;

    ssl_certificate /etc/letsencrypt/live/utkarshtyagi.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/utkarshtyagi.in/privkey.pem;

    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 443 ssl;

    server_name www.utkarshtyagi.in;

    ssl_certificate /etc/letsencrypt/live/utkarshtyagi.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/utkarshtyagi.in/privkey.pem;

    return 301 https://utkarshtyagi.in$request_uri;
}