server {
    listen 80;
    server_name utkarshtyagi.in www.utkarshtyagi.in;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://utkarshtyagi.in$request_uri;
    }
}